USE COVID_19;
SELECT * FROM MOHFW ORDER BY 5;

CREATE TABLE [STATE]
(STATE_ID INT IDENTITY(1,1),
[STATE] NVARCHAR(100));
ALTER TABLE STATE ADD CONSTRAINT PK_STATE PRIMARY KEY(STATE_ID);

INSERT INTO [STATE] SELECT DISTINCT STATE FROM MOHFW
WHERE State NOT IN (SELECT DISTINCT STATE FROM STATE);

SELECT * FROM STATE;

CREATE TABLE [DATE]
(DATE_ID INT IDENTITY(1,1),
[DATE] DATETIME);
ALTER TABLE DATE ADD CONSTRAINT PK_DATE PRIMARY KEY(DATE_ID);

INSERT INTO [DATE] SELECT DISTINCT DATE FROM MOHFW
WHERE Date NOT IN (SELECT DISTINCT Date FROM DATE);

SELECT * FROM DATE;

ALTER TABLE CONFIRMED_CASES ADD CONSTRAINT FK_CON_DATE FOREIGN KEY (CON_DATE_ID) REFERENCES DATE(DATE_ID);
ALTER TABLE CONFIRMED_CASES ADD CONSTRAINT FK_CON_STATE FOREIGN KEY (CON_STATE_ID) REFERENCES STATE(STATE_ID);
CREATE TABLE CONFIRMED_CASES
(CON_ID INT IDENTITY(1,1) PRIMARY KEY
,CON_DATE_ID INT REFERENCES DATE(DATE_ID)
,CON_STATE_ID INT REFERENCES STATE(STATE_ID)
,CONFIRMED_CASES INT);

INSERT INTO CONFIRMED_CASES
(CON_DATE_ID
,CON_STATE_ID
,CONFIRMED_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,CONFIRMED_CASES_ON_THIS_DAY
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
UPDATE ACTIVE_CASES SET ACT_STATE_ID = 26
WHERE ACT_STATE_ID IN (1,11)

--QC
SELECT *
FROM MOHFW M
--JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE = '2020-01-30 00:00:00.000'
ORDER BY 5

SELECT * FROM CONFIRMED_CASES C
JOIN STATE S ON C.CON_STATE_ID = S.STATE_ID
JOIN DATE D ON C.CON_DATE_ID = D.DATE_ID ORDER BY DATE


CREATE TABLE CURED_CASES
(CUR_ID INT IDENTITY(1,1) PRIMARY KEY
,CUR_DATE_ID INT REFERENCES DATE(DATE_ID)
,CUR_STATE_ID INT REFERENCES STATE(STATE_ID)
,CURED_CASES INT);
GO
ALTER TABLE CURED_CASES ADD CONSTRAINT FK_CUR_DATE FOREIGN KEY  (CUR_DATE_ID) REFERENCES DATE(DATE_ID);
ALTER TABLE CURED_CASES ADD CONSTRAINT FK_CUR_STATE FOREIGN KEY (CUR_STATE_ID) REFERENCES STATE(STATE_ID);

INSERT INTO CURED_CASES
(CUR_DATE_ID
,CUR_STATE_ID
,CURED_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,Recovered_cases_on_this_day
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE

TRUNCATE TABLE DEATH_CASES;

ALTER TABLE DEATH_CASES ADD CONSTRAINT FK_DEATH_DATE FOREIGN KEY  (DEATH_DATE_ID) REFERENCES DATE(DATE_ID);
ALTER TABLE DEATH_CASES ADD CONSTRAINT FK_DEATH_STATE FOREIGN KEY (DEATH_STATE_ID) REFERENCES STATE(STATE_ID);

CREATE TABLE DEATH_CASES
(DEATH_ID INT IDENTITY(1,1) PRIMARY KEY
,DEATH_DATE_ID INT REFERENCES DATE(DATE_ID)
,DEATH_STATE_ID INT REFERENCES STATE(STATE_ID)
,DEATH_CASES INT);
GO
INSERT INTO DEATH_CASES
(DEATH_DATE_ID
,DEATH_STATE_ID
,DEATH_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,Death_cases_on_this_day
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE

----DELTA LOAD
USE COVID_19;

SELECT * FROM MOHFW ORDER BY 5 ASC;

SELECT * FROM [STATE];

INSERT INTO STATE(STATE)
SELECT State FROM MOHFW WHERE State NOT IN (SELECT DISTINCT State FROM STATE);

SELECT * FROM [DATE];

INSERT INTO DATE(DATE)
SELECT DISTINCT DATE FROM MOHFW WHERE DATE > (SELECT MAX(DATE) FROM DATE);

INSERT INTO CONFIRMED_CASES
(CON_DATE_ID
,CON_STATE_ID
,CONFIRMED_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,CONFIRMED_CASES_ON_THIS_DAY
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID > (SELECT MAX(CON_DATE_ID) FROM CONFIRMED_CASES);

SELECT * FROM CONFIRMED_CASES;

INSERT INTO CURED_CASES
(CUR_DATE_ID
,CUR_STATE_ID
,CURED_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,Recovered_cases_on_this_day
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID > (SELECT MAX(CUR_DATE_ID) FROM CURED_CASES);

INSERT INTO DEATH_CASES
(DEATH_DATE_ID
,DEATH_STATE_ID
,DEATH_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,Death_cases_on_this_day
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID > (SELECT MAX(DEATH_DATE_ID) FROM DEATH_CASES)


CREATE TABLE ACTIVE_CASES
(ACT_ID INT IDENTITY(1,1) PRIMARY KEY
,ACT_DATE_ID INT REFERENCES DATE(DATE_ID)
,ACT_STATE_ID INT REFERENCES STATE(STATE_ID)
,ACTIVE_CASES INT);
GO
ALTER TABLE ACTIVE_CASES ADD CONSTRAINT FK_ACT_DATE FOREIGN KEY  (ACT_DATE_ID) REFERENCES DATE(DATE_ID);
ALTER TABLE ACTIVE_CASES ADD CONSTRAINT FK_ACT_STATE FOREIGN KEY (ACT_STATE_ID) REFERENCES STATE(STATE_ID);


SELECT * FROM CONFIRMED_CASES C
JOIN DATE D ON C.CON_DATE_ID = D.DATE_ID
ORDER BY DATE;

INSERT INTO ACTIVE_CASES
(ACT_DATE_ID
,ACT_STATE_ID
,ACTIVE_CASES)
SELECT DISTINCT
D.DATE_ID
,S.STATE_ID
,Total_Active
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID > (SELECT MAX(ACT_DATE_ID) FROM ACTIVE_CASES)

SELECT DATE,COUNT(1) FROM MOHFW
GROUP BY DATE
ORDER BY Date;

SELECT * FROM CONFIRMED_CASES

INSERT INTO CONFIRMED_CASES
(CON_DATE_ID
,CON_STATE_ID
,CONFIRMED_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,CONFIRMED_CASES_ON_THIS_DAY
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID = 160
AND S.STATE_ID NOT IN (SELECT DISTINCT CON_STATE_ID FROM CONFIRMED_CASES WHERE CON_DATE_ID = 160)

INSERT INTO CURED_CASES
(CUR_DATE_ID
,CUR_STATE_ID
,CURED_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,Recovered_cases_on_this_day
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID = 159
AND S.STATE_ID NOT IN (SELECT DISTINCT CUR_STATE_ID FROM CURED_CASES WHERE CUR_DATE_ID = 159)

INSERT INTO DEATH_CASES
(DEATH_DATE_ID
,DEATH_STATE_ID
,DEATH_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,Death_cases_on_this_day
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
WHERE D.DATE_ID = 160
AND S.STATE_ID NOT IN (SELECT DISTINCT DEATH_STATE_ID FROM DEATH_CASES WHERE DEATH_DATE_ID = 160);

SELECT * FROM ACTIVE_CASES ORDER BY ACT_DATE_ID;

TRUNCATE TABLE ACTIVE_CASES;

INSERT INTO ACTIVE_CASES
(ACT_DATE_ID
,ACT_STATE_ID
,ACTIVE_CASES)
SELECT
D.DATE_ID
,S.STATE_ID
,(C.CONFIRMED_CASES - (CU.CURED_CASES + DE.DEATH_CASES))
FROM MOHFW M
JOIN STATE S ON M.STATE = S.STATE
JOIN DATE D ON M.DATE = D.DATE
JOIN CONFIRMED_CASES C ON CON_DATE_ID = D.DATE_ID AND CON_STATE_ID = S.STATE_ID
JOIN CURED_CASES CU ON CUR_DATE_ID = D.DATE_ID AND CUR_STATE_ID = S.STATE_ID
JOIN DEATH_CASES DE ON DEATH_DATE_ID = D.DATE_ID AND DEATH_STATE_ID = S.STATE_ID
ORDER BY S.STATE_ID